---

name: NodeJS CI test

on: 
  push:
    branches: ["main", "test*"]
    tags: ["v1.*.*"]
  pull_request:
    branches: ["main"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
  steps:
  - uses: actions/checkout@v3

  - name: Use node.js
    uses: actions/setup-node@v3
    whit:
      ned-version: 18
      cache: 'npm'

  - name: Install NPM packages
  run: npm install

  -name: Run test
      run: npm test
  
